services:
  - type: web
    name: eda-agent-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
    region: oregon

files:
  - app.py
  - agent.py
  - eda_utils.py
  - requirements.txt
  - data/demo_creditcard_fraud.csv
